server:
  port: 80
  tomcat:
    max-threads: 2000

spring:
  application:
    name: api-gateway
  cache:
    ehcache:
      config: ehcache.xml
  redis:
    database: 1
    host: 192.168.106.76
    port: 6379
    password: Hello1234
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 300000

zuul:
  #  strip-prefix: true
  # 指定路由前缀,所有请求均需要带此前缀
  prefix: /api
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #API网关配置
  #路由配置
  routes:
    #    auth:    #认证服务
    #      #响应的路径
    #      path: /auth/**
    #      #敏感头信息
    #      sensitiveHeaders:
    #      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
    #      serviceId:  auth-server
    #    producer: #生产者服务
    #      #响应的路径
    #      path: /aplus-thirdparty/**
    #      sensitiveHeaders:
    #      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
    #      serviceId:  aplus-thirdparty
    aplus-thirdparty:
      ##默认请求不带前缀 需要加上 stripPrefix: false让所有请求带前缀
      stripPrefix: false
      path: /aplus-thirdparty/*
      service-id: aplus-thirdparty
    aplus-user:
      stripPrefix: false
      path: /aplus-user/*
      service-id: aplus-user
  #添加代理头
  add-proxy-headers: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

##接口白名单，以"，"号分割 此处用于图片或者登陆注册不需要鉴权的接口使用后期会加到redis或者mysql中
routesurl:
  /api/aplus-thirdparty/get,/api/aplus-user/login,/api/aplus-user/register



