spring:
  application:
    name: news-discovery-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: peer1              # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756