server:
  port: 8762

spring:
  application:
    name: news-discovery-eureka

eureka:
  instance:
    hostname: peer2             # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/