spring:
  application:
    name: news-discovery-eureka

server:
  port: 9761


eureka:
  instance:
    ip-address: 192.168.106.92# 指定此实例的ip
    prefer-ip-address: true # 注册时使用ip而不是主机名
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    fetch-registry: false
    register-with-eureka: false




